
# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME

scroll_smooth true
smooth_scroll_min_wait_time 300
smooth_scroll_max_wait_time 5000
smooth_scroll_end_capability 5

cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
cursor_shape beam

sync_to_monitor yes

font_family      JetbrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13

shell zsh
