source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/binds.conf
source = ~/.config/hypr/config/envVariables.conf
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/decoration.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/workspace.conf
