animations {
    enabled = yes

    bezier = easeoutquint,   0.23, 1,    0.32, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostlinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = bounce,     0.68, -0.55, 0.27, 1.55   # overshoots then settles
    bezier = smoothout,  0.36, 0,     0.66, -0.56  # starts fast, snaps back
    bezier = expo,       0.16, 1,     0.3,  1       # very snappy start, long tail

    animation = windows,    1, 1,  quick, slide top
    animation = border,     1, 5.39, expo
    animation = fade,       1, 2,    linear
    animation = layers,     1, 1, linear
    animation = workspaces, 1, 2,  quick, slidefade 40%
}
