general {
    gaps_in = 8
    gaps_out = 14
    resize_on_border = false
    border_size = 0
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 8
    rounding_power = 3

    active_opacity   = 0.95
    inactive_opacity = 0.75

    shadow {
        enabled      = false
        range        = 20
    }

    blur {
      enabled = true
      size = 4
      passes = 3
      ignore_opacity = true
      
      noise = 0.01
      contrast = 5

      xray = false
      new_optimizations = true
    }
}
